name: nn-py310
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.10  # Python 3.10으로 업그레이드
  - pip
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyter
  - ipykernel
  - pillow
  - h5py
  - cudatoolkit=11.8  # CUDA 11.8로 업데이트
  - pip:
    - tensorflow==2.15.0
    - nvidia-cudnn-cu11==8.9.4.25
    - torch==2.5.1+cu118
    - torchvision==0.20.1+cu118
    - torchaudio==2.5.1+cu118